import {Categories} from "../IconBaseClass";
/*
    Teleports

    Basic one point teleports that appear as markers wit any icon

 */
export const Teleports = [
    // >>>>>>>>>>>>>>>>>>>>> Standard Spell book >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
        iconUrl: require('../../../static/icons/teleport/Home_Teleport_icon.png'),
        className: 'teleport teleport_home ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 76.35967119570851, "lng": 317},
        title: "Home Teleport Spell",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",

    },
    {
        iconUrl: require('../../../static/icons/teleport/Lumbridge_Teleport_icon.png'),
        className: 'teleport teleport_lumbridge ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 76.35967119570851, "lng": 317.3},
        title: "Teleport to Lumbridge",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Varrock_Teleport_icon.png'),
        className: 'teleport teleport_varrock ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 79.19401548509859, "lng": 316.37329101562506},
        title: "Teleport to Varrock",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Falador_Teleport_icon.png'),
        className: 'teleport teleport_faladaor ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 78.66244812600279, "lng": 300.06408691406256},
        title: "Teleport to Falador",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_to_House_icon.png'),
        className: 'teleport teleport_house teleport_rimmington ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 76.43718024219102, "lng": 299.33898925781256},
        title: "Teleport to House (Rimmington)",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_to_House_icon.png'),
        className: 'teleport teleport_house teleport_yannile ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 74.27909894347644, "lng": 272.32360839843756},
        title: "Teleport to House (Yannille)",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_to_House_icon.png'),
        className: 'teleport teleport_house teleport_rellekka ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 81.50935493057601, "lng": 280.56884765625006},
        title: "Teleport to House (Rellekka)",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_to_House_icon.png'),
        className: 'teleport teleport_house teleport_brimhaven ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 75.70342995730704, "lng": 286.46850585937506},
        title: "Teleport to House (Brimhaven)",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_to_House_icon.png'),
        className: 'teleport teleport_house teleport_taverly ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 79.69701350577613, "lng": 295.46081542968756},
        title: "Teleport to House (Taverly)",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_to_House_icon.png'),
        className: 'teleport teleport_house teleport_pollnivneach ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 72.6038360424019, "lng": 324.73388671875006},
        title: "Teleport to House (Pollnivneach)",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_to_House_icon.png'),
        className: 'teleport teleport_house teleport_hosidius ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 80.29607550360463, "lng": 219.63867187500003},
        title: "Teleport to House (Hosidius)",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Camelot_Teleport_icon.png'),
        className: 'teleport teleport_camelot ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 79.84818858331862, "lng": 286.38061523437506},
        title: "Teleport to Camelot",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ardougne_Teleport_icon.png'),
        className: 'teleport teleport_ardougne ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 77.64712256067553, "lng": 280.04150390625006},
        title: "Teleport to Ardougne",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Watchtower_Teleport_icon.png'),
        className: 'teleport teleport_watchtower ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 74.63238139647521, "lng": 272.51037597656256},
        title: "Teleport to the Watchtower",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Trollheim_Teleport_icon.png'),
        className: 'teleport teleport_trollheim ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 81.92164259401909, "lng": 295.20263671875006},
        title: "Teleport to Trollheim",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ape_Atoll_Teleport_%28standard%29_icon.png'),
        className: 'teleport teleport_apeatol ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 67.86519487931152, "lng": 289.03930664062506},
        title: "Teleport to Ape Atol",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kourend_Castle_Teleport_icon.png'),
        className: 'teleport teleport_kourendcastle ' + Categories.REGULAR_SPELLBOOK,
        position: {"lat": 81.88295389538273, "lng": 213.01391601562503},
        title: "Teleport to Kourend Castle",
        category: Categories.REGULAR_SPELLBOOK,
        description: "",
    },
    // <<<<<<<<<<<<<<<<<<<<< Standard Spell book <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    // >>>>>>>>>>>>>>>>>>>>> Ancient Spell book >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
        iconUrl: require('../../../static/icons/teleport/Paddewwa_Teleport_icon.png'),
        className: 'teleport teleport_paddewwa ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat": 79.85302848224637, "lng": 308.58947753906256},
        title: "Teleport to Paddewwa",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Senntisten_Teleport_icon.png'),
        className: 'teleport teleport_senntisten ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat": 78.1344931829381, "lng": 325.71166992187506},
        title: "Teleport to Paddewwa",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kharyrll_Teleport_icon.png'),
        className: 'teleport teleport_kharyrll ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat": 79.95509868922989, "lng": 334.85778808593756},
        title: "Teleport to Kharyrll ",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Lassar_Teleport_icon.png'),
        className: 'teleport teleport_lassar ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat": 79.9799791857134, "lng": 302.9095458984375},
        title: "Teleport to Lassar ",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Dareeyak_Teleport_icon.png'),
        className: 'teleport teleport_dareeyak ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat": 82.08290127808056, "lng": 300.44860839843756},
        title: "Teleport to Dareeyak",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Carrallangar_Teleport_icon.png'),
        className: 'teleport teleport_carrallangar ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat": 81.88140252510168, "lng": 313.34106445312506},
        title: "Teleport to Carrallangar ",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Annakarl_Teleport_icon.png'),
        className: 'teleport teleport_annakarl ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat": 83.63932291491399, "lng": 321.41601562500006},
        title: "Teleport to Annakarl ",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ghorrock_Teleport_icon.png'),
        className: 'teleport teleport_ghorrock ' + Categories.ANCIENT_SPELLBOOK,
        position: {"lat":83.53749710311818,"lng":300.36621093750006},
        title: "Teleport to Ghorrock ",
        category: Categories.ANCIENT_SPELLBOOK,
        description: "",
    },
    // <<<<<<<<<<<<<<<<<<<<< Ancient Spell book <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    // >>>>>>>>>>>>>>>>>>>>> Lunar Spell book >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
        iconUrl: require('../../../static/icons/teleport/Home_Teleport_icon.png'),
        className: 'teleport teleport_lunar_home ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":83.84292070051193,"lng":242.73193359375003},
        title: "Home Teleport Spell (Lunar)",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Moonclan_Teleport_icon.png'),
        className: 'teleport teleport_moonclan ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":83.8399741628462,"lng":243.09997558593753},
        title: "Moonclan Teleport",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ourania_Teleport_icon.png'),
        className: 'teleport teleport_ourania teleport_zmi ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":76.72653088877502,"lng":267.50610351562506},
        title: "Ourania Teleport",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Waterbirth_Teleport_icon.png'),
        className: 'teleport teleport_waterbirth ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":82.64822196607551,"lng":272.20825195312506},
        title: "Waterbirth Teleport",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Barbarian_Teleport_icon.png'),
        className: 'teleport teleport_barbiarn_outpost ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":80.84402736160101,"lng":270.68115234375006},
        title: "Barbarian Teleport (Barbarian Outpost)",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Khazard_Teleport_icon.png'),
        className: 'teleport teleport_khazard ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":75.38392435449046,"lng":279.63500976562506},
        title: "Khazard Teleport",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Fishing_Guild_Teleport_icon.png'),
        className: 'teleport teleport_fishing_guild ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":78.7827617628182,"lng":276.71264648437506},
        title: "Fishing Guild Teleport",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Catherby_Teleport_icon.png'),
        className: 'teleport teleport_catherby ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":79.50766114392374,"lng":289.12719726562506},
        title: "Catherby Teleport",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ice_Plateau_Teleport_icon.png'),
        className: 'teleport teleport_ice_plateau ' + Categories.LUNAR_SPELLBOOK,
        position: {"lat":83.86878976571622,"lng":300.42114257812506},
        title: "Ice Planteau Teleport",
        category: Categories.LUNAR_SPELLBOOK,
        description: "",
    },
    // <<<<<<<<<<<<<<<<<<<<< Lunar Spell book <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    // >>>>>>>>>>>>>>>>>>>>> Arceuus Spell book >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
        iconUrl: require('../../../static/icons/teleport/Home_Teleport_icon.png'),
        className: 'teleport teleport_home_arceuus ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":83.60454003128096,"lng":217.05688476562503},
        title: "Home Teleport Spell (Arceuus)",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Lumbridge_Graveyard_Teleport_icon.png'),
        className: 'teleport teleport_lumbridge_graveyard ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":76.01742102194744,"lng":318.37280273437506},
        title: "Lumbridge Graveyard Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Draynor_Manor_Teleport_icon.png'),
        className: 'teleport teleport_draynor_manor ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":78.13901024442676,"lng":309.57275390625006},
        title: "Draynor Manor Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Battlefront_Teleport_icon.png'),
        className: 'teleport teleport_battlefront ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":82.46966951033005,"lng":193.52416992187503},
        title: "Battlefront Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Mind_Altar_Teleport_icon.png'),
        className: 'teleport teleport_mind_altar ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":80.10252542210563,"lng":301.01989746093756},
        title: "Mind Altar Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Respawn_Teleport_icon.png'),
        className: 'teleport teleport_respawn_edgeville ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":79.78895756946126,"lng":308.594970703125},
        title: "Respawn Teleport ",
        description: "Must have death location here",
        category: Categories.ARCEUUS_SPELLBOOK
    },
    {
        iconUrl: require('../../../static/icons/teleport/Respawn_Teleport_icon.png'),
        className: 'teleport teleport_respawn_lumbridge ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":76.28303027845439,"lng":317.14233398437506},
        title: "Respawn Teleport ",
        description: "Must have death location here",
        category: Categories.ARCEUUS_SPELLBOOK
    },
    {
        iconUrl: require('../../../static/icons/teleport/Respawn_Teleport_icon.png'),
        className: 'teleport teleport_respawn_falador ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":78.14013924493644,"lng":300.44311523437506},
        title: "Respawn Teleport ",
        description: "Must have death location here",
        category: Categories.ARCEUUS_SPELLBOOK
    },
    {
        iconUrl: require('../../../static/icons/teleport/Respawn_Teleport_icon.png'),
        className: 'teleport teleport_respawn_ardougne ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":77.65064755611985,"lng":279.72290039062506},
        title: "Respawn Teleport ",
        description: "Must have death location here",
        category: Categories.ARCEUUS_SPELLBOOK
    },
    {
        iconUrl: require('../../../static/icons/teleport/Salve_Graveyard_Teleport_icon.png'),
        className: 'teleport teleport_salve_graveyard ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":79.66749761579231,"lng":330.83129882812506},
        title: "Salve Graveyard Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Fenkenstrain%27s_Castle_Teleport_icon.png'),
        className: 'teleport teleport_fenkenstrains_castle ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":80.4248491549027,"lng":338.56567382812506},
        title: "Fenkenstrain's Castle Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/West_Ardougne_Teleport_icon.png'),
        className: 'teleport teleport_western_ardounge ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":77.62948272019062,"lng":268.01147460937506},
        title: "Western Ardougne Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/West_Ardougne_Teleport_icon.png'),
        className: 'teleport teleport_western_ardounge ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":77.62948272019062,"lng":268.01147460937506},
        title: "Western Ardougne Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Harmony_Island_Teleport_icon.png'),
        className: 'teleport teleport_harmoney_island ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":69.57097878993854,"lng":354.93530273437506},
        title: "Harmoney Island Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Cemetery_Teleport_icon.png'),
        className: 'teleport teleport_forgotten_cemetery ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":82.57617631552547,"lng":300.87158203125006},
        title: "Forgotten Cemetery Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Barrows_Teleport_icon.png'),
        className: 'teleport teleport_barrows ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":77.77572686730878,"lng":339.6478271484375},
        title: "Barrows Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ape_Atoll_Teleport_%28Arceuus%29_icon.png'),
        className: 'teleport teleport_ape_atol ' + Categories.ARCEUUS_SPELLBOOK,
        position: {"lat":65.4924628822755,"lng":286.33117675781256},
        title: "Ape Atol Teleport",
        category: Categories.ARCEUUS_SPELLBOOK,
        description: "",
    },
    // <<<<<<<<<<<<<<<<<<<<< Arceuus Spell book <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    // >>>>>>>>>>>>>>>>>>>>> Jewellery >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
        iconUrl: require('../../../static/icons/teleport/Games_necklace.png'),
        className: 'jewellery games_necklace ' + Categories.JEWELLERY,
        position: {"lat":80.90587943024157,"lng":270.75805664062506},
        title: "Games Necklance Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Games_necklace.png'),
        className: 'jewellery games_necklace ' + Categories.JEWELLERY,
        position: {"lat":80.67911826095326,"lng":295.68603515625006},
        title: "Games Necklance Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Games_necklace.png'),
        className: 'jewellery games_necklace ' + Categories.JEWELLERY,
        position: {"lat":84.00455785504411,"lng":211.67907714843753},
        title: "Games Necklance Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ring_of_dueling.png'),
        className: 'jewellery ring_of_dueling ' + Categories.JEWELLERY,
        position: {"lat":74.16558439057223,"lng":265.56152343750006},
        title: "Ring of Dueling Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ring_of_dueling.png'),
        className: 'jewellery ring_of_dueling ' + Categories.JEWELLERY,
        position: {"lat":76.59090394154062,"lng":323.29467773437506},
        title: "Ring of Dueling Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ring_of_dueling.png'),
        className: 'jewellery ring_of_dueling ' + Categories.JEWELLERY,
        position: {"lat":75.39500943841519,"lng":327.96386718750006},
        title: "Ring of Dueling Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Combat_bracelet.png'),
        className: 'jewellery combat_bracelet ' + Categories.JEWELLERY,
        position: {"lat":80.03050836819759,"lng":305.78247070312506},
        title: "Combat Bracelet Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Combat_bracelet.png'),
        className: 'jewellery combat_bracelet ' + Categories.JEWELLERY,
        position: {"lat":78.46751192571969,"lng":314.97253417968756},
        title: "Combat Bracelet Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Combat_bracelet.png'),
        className: 'jewellery combat_bracelet ' + Categories.JEWELLERY,
        position: {"lat":80.6121540861832,"lng":294.40612792968756},
        title: "Combat Bracelet Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Combat_bracelet.png'),
        className: 'jewellery combat_bracelet ' + Categories.JEWELLERY,
        position: {"lat":79.41623981214111,"lng":279.65698242187506},
        title: "Combat Bracelet Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Skills_necklace.png'),
        className: 'jewellery skills_necklace ' + Categories.JEWELLERY,
        position: {"lat":78.78169313024124,"lng":277.08068847656256},
        title: "Skills Necklace Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Skills_necklace.png'),
        className: 'jewellery skills_necklace ' + Categories.JEWELLERY,
        position: {"lat":78.09829559916763,"lng":303.93676757812506},
        title: "Skills Necklace Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Skills_necklace.png'),
        className: 'jewellery skills_necklace ' + Categories.JEWELLERY,
        position: {"lat":82.28828054353076,"lng":186.910400390625},
        title: "Skills Necklace Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Skills_necklace.png'),
        className: 'jewellery skills_necklace ' + Categories.JEWELLERY,
        position: {"lat":77.480325861269,"lng":298.03710937500006},
        title: "Skills Necklace Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Skills_necklace.png'),
        className: 'jewellery skills_necklace ' + Categories.JEWELLERY,
        position: {"lat":79.41220327334501,"lng":311.824951171875},
        title: "Skills Necklace Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Skills_necklace.png'),
        className: 'jewellery skills_necklace ' + Categories.JEWELLERY,
        position: {"lat":80.15432156203568,"lng":214.12353515625003},
        title: "Skills Necklace Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Amulet_of_glory.png'),
        className: 'jewellery amulet_of_glory ' + Categories.JEWELLERY,
        position: {"lat":75.46548375087849,"lng":321.66870117187506},
        title: "Amulet of Glory Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Amulet_of_glory.png'),
        className: 'jewellery amulet_of_glory ' + Categories.JEWELLERY,
        position: {"lat":76.81703471551978,"lng":309.13330078125006},
        title: "Amulet of Glory Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Amulet_of_glory.png'),
        className: 'jewellery amulet_of_glory ' + Categories.JEWELLERY,
        position: {"lat":80.12892798946548,"lng":308.0841064453125},
        title: "Amulet of Glory Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Amulet_of_glory.png'),
        className: 'jewellery amulet_of_glory ' + Categories.JEWELLERY,
        position: {"lat":75.56988730054205,"lng":297.09228515625006},
        title: "Amulet of Glory Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ring_of_wealth.png'),
        className: 'jewellery ring_of_wealth ' + Categories.JEWELLERY,
        position: {"lat":79.6930828778363,"lng":313.24768066406256},
        title: "Ring of Wealth Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ring_of_wealth.png'),
        className: 'jewellery ring_of_wealth ' + Categories.JEWELLERY,
        position: {"lat":78.64082992043338,"lng":302.05261230468756},
        title: "Ring of Wealth Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ring_of_wealth.png'),
        className: 'jewellery ring_of_wealth ' + Categories.JEWELLERY,
        position: {"lat":83.46412945073891,"lng":271.70837402343756},
        title: "Ring of Wealth Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Slayer_ring.png'),
        className: 'jewellery slayer_ring ' + Categories.JEWELLERY,
        position: {"lat":80.44675403034532,"lng":330.67749023437506},
        title: "Ring of Slayer Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Slayer_ring.png'),
        className: 'jewellery slayer_ring ' + Categories.JEWELLERY,
        position: {"lat":81.31661808728937,"lng":288.51196289062506},
        title: "Ring of Slayer Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Slayer_ring.png'),
        className: 'jewellery slayer_ring ' + Categories.JEWELLERY,
        position: {"lat":79.20842430283616,"lng":265.37475585937506},
        title: "Ring of Slayer Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Digsite_pendant.png'),
        className: 'jewellery digsite_pendent ' + Categories.JEWELLERY,
        position: {"lat":79.44646539760868,"lng":325.228271484375},
        title: "Digsite Pendent Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Digsite_pendant.png'),
        className: 'jewellery digsite_pendent ' + Categories.JEWELLERY,
        position: {"lat":83.5220218873171,"lng":352.74902343750006},
        title: "Digsite Pendent Teleport",
        description: "Works after bone voyage complete but have to use the pendent on the south strange machine within the house on the hill first",
        category: Categories.JEWELLERY
    },
    {
        iconUrl: require('../../../static/icons/teleport/Digsite_pendant.png'),
        className: 'jewellery digsite_pendent ' + Categories.JEWELLERY,
        position: {"lat":84.42998562277383,"lng":338.9666748046875},
        title: "Digsite Pendent Teleport",
        description: "Works after dragon slayer 2, but have to come down this dungeon manually and use pendent on the strange machine again",
        category: Categories.JEWELLERY
    },
    {
        iconUrl: require('../../../static/icons/teleport/Necklace_of_passage.png'),
        className: 'jewellery necklace_of_passage ' + Categories.JEWELLERY,
        position: {"lat":75.71969873605714,"lng":309.89135742187506},
        title: "Necklace of Passage Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Necklace_of_passage.png'),
        className: 'jewellery necklace_of_passage ' + Categories.JEWELLERY,
        position: {"lat":78.2121753659723,"lng":264.76501464843756},
        title: "Necklace of Passage Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Necklace_of_passage.png'),
        className: 'jewellery necklace_of_passage ' + Categories.JEWELLERY,
        position: {"lat":75.30331101068566,"lng":329.22729492187506},
        title: "Necklace of Passage Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Burning_amulet.png'),
        className: 'jewellery burning_amulet ' + Categories.JEWELLERY,
        position: {"lat":81.52798885197393,"lng":317.90039062500006},
        title: "Burning Amulet Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Burning_amulet.png'),
        className: 'jewellery burning_amulet ' + Categories.JEWELLERY,
        position: {"lat":81.66605710511882,"lng":305.13427734375006},
        title: "Burning Amulet Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Burning_amulet.png'),
        className: 'jewellery burning_amulet ' + Categories.JEWELLERY,
        position: {"lat":83.30849930404761,"lng":304.23339843750006},
        title: "Burning Amulet Teleport",
        category: Categories.JEWELLERY,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ectophial.png'),
        className: 'item_icon ectophial ' + Categories.OTHER,
        position: {"lat":80.31919594760542,"lng":345.87158203125006},
        title: "Ectophial Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Nardah_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":70.7688246201659,"lng":330.05126953125006},
        title: "Nardah Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Digsite_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":79.0676456861466,"lng":323.89343261718756},
        title: "Digsite Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Elf_camp_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":76.96033358827414,"lng":249.24682617187503},
        title: "Elf Camp Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Feldip_hills_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":70.96865539856438,"lng":272.08190917968756},
        title: "Feldip Hills Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Lumberyard_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":79.93879762178535,"lng":322.2564697265625},
        title: "Lumberyard Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Lunar_isle_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":83.84233150531966,"lng":242.39135742187503},
        title: "Lunar Isles Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Mort%27ton_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":77.41346715054658,"lng":334.54467773437506},
        title: "Mort'ton Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Pest_control_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":64.34942106230751,"lng":279.82177734375006},
        title: "Pest Control Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Piscatoris_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":81.65809140450546,"lng":258.92578125000006},
        title: "Picsatoris Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Tai_bwo_wannai_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":73.72967302053397,"lng":288.29772949218756},
        title: "Tai Bwo Wannai Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Mos_le%27harmless_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":72.425585600905,"lng":348.58520507812506},
        title: "Mos Le'Harmless Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Zul-andra_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":73.57506106401794,"lng":249.37866210937503},
        title: "Zul-andra Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Revenant_cave_teleport.png'),
        className: 'clue_scroll_teleports ' + Categories.OTHER,
        position: {"lat":83.23642648170203,"lng":310.95703125000006},
        title: "Revenant Cave Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Stony_basalt.png'),
        className: 'troll_teleports ' + Categories.OTHER,
        position: {"lat":82.05941121693256,"lng":291.42333984375006},
        title: "Stoney Basalt Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Icy_basalt.png'),
        className: 'troll_teleports ' + Categories.OTHER,
        position: {"lat":84.0228901101526,"lng":292.20336914062506},
        title: "Icy Basalt Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Explorer%27s_ring_2.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":77.42901916452809,"lng":305.91979980468756},
        title: "Explorer's Ring 2/3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Karamja_gloves_3.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":72.40899172812027,"lng":290.90698242187506},
        title: "Karamja Gloves 3 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Karamja_gloves_4.webp'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":72.06714729310255,"lng":293.72497558593756},
        title: "Karamja Gloves 4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ardougne_cloak_1.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":76.44490733708945,"lng":276.37756347656256},
        title: "Ardougne Cloak 1/2/3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Ardougne_cloak_2.webp'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":78.57681893187248,"lng":280.89843750000006},
        title: "Ardougne Cloak 2/3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Desert_amulet_2.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":70.90586245415463,"lng":329.61181640625006},
        title: "Desert Amulet 2/3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Desert_amulet_4.webp'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":74.75563516121497,"lng":323.77258300781256},
        title: "Desert Amulet 4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Morytania_legs_3.webp'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":76.54113226390878,"lng":334.08874511718756},
        title: "Morytania Legs 3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Fremennik_sea_boots_2.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":81.9278157639914,"lng":278.76708984375006},
        title: "Fremennik Sea Boots 1/2/3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kandarin_headgear_3.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":79.15687689247802,"lng":284.91943359375006},
        title: "Kandarin Headgear 3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Wilderness_sword_3.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":83.63079724346103,"lng":327.30468750000006},
        title: "Wilderness Sword 3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Western_banner_3.png'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":81.8284803382328,"lng":259.05212402343756},
        title: "Western Banner 3/4 Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Rada\'s_blessing_1.webp'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":79.58837906830985,"lng":207.10327148437503},
        title: "Rada's Blessing 1/2/3/4",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Rada\'s_blessing_3.webp'),
        className: 'achievement_jewelery item_icon ' + Categories.OTHER,
        position: {"lat":82.9551640476858,"lng":191.04675292968753},
        title: "Rada's Blessing 3/4",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Xeric\'s_talisman_(inert).webp'),
        className: 'xerics_amulet item_icon ' + Categories.OTHER,
        position: {"lat":80.74825879312192,"lng":187.3828125},
        title: "Xeric's Honour",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Xeric\'s_talisman_(inert).webp'),
        className: 'xerics_amulet item_icon ' + Categories.OTHER,
        position: {"lat":80.13739971053121,"lng":221.48437500000003},
        title: "Xeric's Glade",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Xeric\'s_talisman_(inert).webp'),
        className: 'xerics_amulet item_icon ' + Categories.OTHER,
        position: {"lat":81.82691862716233,"lng":212.56896972656253},
        title: "Xeric's Heart",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Xeric\'s_talisman_(inert).webp'),
        className: 'xerics_amulet item_icon ' + Categories.OTHER,
        position: {"lat":83.11238862608707,"lng":203.77441406250003},
        title: "Xeric's Inferno",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Xeric\'s_talisman_(inert).webp'),
        className: 'xerics_amulet item_icon ' + Categories.OTHER,
        position: {"lat":80.4376330387013,"lng":208.39965820312503},
        title: "Xeric's Lookout",
        category: Categories.OTHER,
        description: "",
    },
    // <<<<<<<<<<<<<<<<<<<<< Jewellery <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    // >>>>>>>>>>>>>>>>>>>>> MISC >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    {
        iconUrl: require('../../../static/icons/teleport/Skull_sceptre.webp'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":79.20430943611333,"lng":307.81494140625006},
        title: "Skull Sceptre Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Pharaoh\'s_sceptre.webp'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":70.06745743428272,"lng":317.69714355468756},
        title: "Pharaoh's Sceptre Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Pharaoh\'s_sceptre.webp'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":67.72610818595071,"lng":321.78405761718756},
        title: "Pharaoh's Sceptre Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Pharaoh\'s_sceptre.webp'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":68.74435062211467,"lng":325.86547851562506},
        title: "Pharaoh's Sceptre Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Goblin_village_sphere.webp'),
        className: Categories.OTHER,
        position: {"lat":80.11479244077704,"lng":299.38842773437506},
        title: "Goblin Village Sphere",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Teleport_crystal.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":75.51365583631552,"lng":258.72802734375006},
        title: "Teleport Crystal Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Royal_seed_pod.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":80.0409639072338,"lng":267.18750000000006},
        title: "Royal Seed Pod Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Enchanted_lyre.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":81.86587261475073,"lng":278.87695312500006},
        title: "Enchanted Lyre Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Camulet.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":70.92023268949522,"lng":314.64843750000006},
        title: "Camulet Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Drakan%27s_medallion.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":76.35319252705754,"lng":345.52551269531256},
        title: "Drakan's Medallion Teleport",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kharedst%27s_memoirs.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":81.29752279516099,"lng":217.44140625000003},
        title: "Lunch by the lancalliums (Kharedst's memoirs)",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kharedst%27s_memoirs.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":82.54773185359726,"lng":223.60473632812503},
        title: "The fisher's flute (Kharedst's memoirs)",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kharedst%27s_memoirs.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":80.96472954372805,"lng":201.96166992187503},
        title: "History and hearsay (Kharedst's memoirs)",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kharedst%27s_memoirs.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":82.68817947393305,"lng":206.66381835937503},
        title: "Jewellery of jubilation (Kharedst's memoirs)",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Kharedst%27s_memoirs.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":82.56196760521456,"lng":215.37597656250003},
        title: "A dark disposition (Kharedst's memoirs)",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":74.23886253330774,"lng":265.41320800781256},
        title: "Mini-game Teleport",
        description: "Castle Wars",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":80.85625646902527,"lng":271.48315429687506},
        title: "Mini-game Teleport",
        description: "Barbarian Assault",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":80.81513741046767,"lng":295.80688476562506},
        title: "Mini-game Teleport",
        description: "Burthorpe Gamesroom",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":75.39500943841519,"lng":327.05200195312506},
        title: "Mini-game Teleport",
        description: "Clan Wars",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":75.4585892414553,"lng":280.44799804687506},
        title: "Mini-game Teleport",
        description: "Fishing Trawler",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":74.64402309117955,"lng":276.42150878906256},
        title: "Mini-game Teleport",
        description: "Nightmare Zone",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":64.5035504066553,"lng":279.92614746093756},
        title: "Mini-game Teleport",
        description: "Pest Control",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":76.55774293896556,"lng":303.37646484375006},
        title: "Mini-game Teleport",
        description: "Rat Pits",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":77.47556185051579,"lng":334.94018554687506},
        title: "Mini-game Teleport",
        description: "Shades of Mort'ton",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":81.08981123884188,"lng":222.22045898437503},
        title: "Mini-game Teleport",
        description: "Tithe Farm",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Minigame_icon.webp'),
        className: Categories.MINI_GAMES,
        position: {"lat":72.91802197953525,"lng":355.8526611328125},
        title: "Mini-game Teleport",
        description: "Trouble Brewing",
        category: Categories.MINI_GAMES
    },
    {
        iconUrl: require('../../../static/icons/teleport/Crafting_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":77.35106958476409,"lng":297.94921875000006},
        title: "Crafting Skill Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Fishing_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":79.1496408679084,"lng":275.96008300781256},
        title: "Fishing Skill Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Hunter_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":70.48823599130287,"lng":271.85668945312506},
        title: "Hunter Skill Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Hunter_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":70.48823599130287,"lng":271.85668945312506},
        title: "Hunter Skill Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Strength_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":80.60946562472725,"lng":293.66455078125006},
        title: "Strength Skill Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Quest_point_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":78.20768577248778,"lng":284.44152832031256},
        title: "Quest Pont Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Music_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":80.65238959048843,"lng":281.82128906250006},
        title: "Music Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Achievement_diary_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":76.40235479492847,"lng":308.8531494140625},
        title: "Achievement Diary Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Mythical_cape.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":69.19575089367642,"lng":266.27014160156256},
        title: "Mythical Cape",
        category: Categories.OTHER,
        description: "",
    },
    {
        iconUrl: require('../../../static/icons/teleport/Chronicle.png'),
        className: 'item_icon ' + Categories.OTHER,
        position: {"lat":78.5179207183434,"lng":315.31860351562506},
        title: "Chronicle book",
        category: Categories.OTHER,
        description: "",
    },

];